#!/bin/bash
# First argument is sim_name
# Second argument is reals
# Third argument is config_index

echo config nummer $3

for ((i=1;i<=$2;i++)); do
    python tq_diag.py --sim_name $1 --task_id $i --config_index $3
    echo nummer $i
done
